# Generated by Django 5.2.6 on 2025-10-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
    ]
